#!/usr/bin/env sh
#
# Gradle start up script for POSIX generated by Gradle.
#

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || exit

# NOTE:
# In POSIX sh, quotes inside a variable are literal characters and won't be
# re-interpreted during expansion. The previous value contained embedded quotes
# (e.g. "\"-Xmx64m\""), which caused Java to treat it as a main-class name:
# "Could not find or load main class \"-Xmx64m\"".
#
# Keep this as plain, space-separated JVM args so word splitting yields 2 args.
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ] ; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE="java"
fi

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=gradlew" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"


